FROM ruby:2.5.5-alpine3.9
RUN apk add --no-cache --update build-base \
  linux-headers \
  git \
  postgresql-dev \
  nodejs \
  tzdata


# environment vars must be included in heroku.yml and dockerfile
ARG DATABASE_URL="postgres://postgres@db"
ARG RAILS_MASTER_KEY=e0d4bda96c77ef54b954b6ea7fba7132
ARG RAILS_ENV=production

WORKDIR /myapp
COPY Gemfile /myapp/Gemfile
COPY Gemfile.lock /myapp/Gemfile.lock
RUN gem install bundler && bundle install
COPY . /myapp

# Add a script to be executed every time the container starts.
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
RUN bundle exec rake assets:precompile

EXPOSE 3000

# Start the main process.
CMD ["rails", "server", "-b", "0.0.0.0"] 
