# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
require 'open-uri'
ActiveRecord::Base.connection.execute("DELETE FROM active_storage_attachments")
ActiveRecord::Base.connection.execute("DELETE FROM active_storage_blobs")
User.destroy_all
Artist.destroy_all
Album.destroy_all
Song.destroy_all
Playlist.destroy_all
PlaylistSong.destroy_all

robot = User.create(username: 'botuser', password: 'robots')

artist1 = Artist.create(name: 'Billie Eilish', has_poster: true)
artist1_hero = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Billie%20Eilish/hero.jpg")
artist1.hero_image.attach(io: artist1_hero, filename: 'hero.jpg')
artist1_album1 = Album.create(title: "WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?", artist_id: artist1.id)
artist1_album1_cover = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Billie%20Eilish/WHEN%20WE%20ALL%20FALL%20ASLEEP%2C%20WHERE%20DO%20WE%20GO%3F/cover.jpg")
artist1_album1.album_cover.attach(io: artist1_album1_cover, filename: 'cover.jpg')
artist1_album1_song1 = Song.create(title: "!!!!!!!", length: 14, album_id: artist1_album1.id, explicit: false, album_order: 1)
artist1_album1_song1_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Billie%20Eilish/WHEN%20WE%20ALL%20FALL%20ASLEEP%2C%20WHERE%20DO%20WE%20GO%3F/01%20!!!!!!!.mp3")
artist1_album1_song1.track.attach(io: artist1_album1_song1_mp3, filename: '01 !!!!!!!.mp3')
artist1_album1_song2 = Song.create(title: "bad guy", length: 195, album_id: artist1_album1.id, explicit: false, album_order: 2)
artist1_album1_song2_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Billie%20Eilish/WHEN%20WE%20ALL%20FALL%20ASLEEP%2C%20WHERE%20DO%20WE%20GO%3F/02%20bad%20guy.mp3")
artist1_album1_song2.track.attach(io: artist1_album1_song2_mp3, filename: '02 bad guy.mp3')
artist1_album1_song3 = Song.create(title: "xanny", length: 244, album_id: artist1_album1.id, explicit: false, album_order: 3)
artist1_album1_song3_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Billie%20Eilish/WHEN%20WE%20ALL%20FALL%20ASLEEP%2C%20WHERE%20DO%20WE%20GO%3F/03%20xanny.mp3")
artist1_album1_song3.track.attach(io: artist1_album1_song3_mp3, filename: '03 xanny.mp3')
artist1_album1_song4 = Song.create(title: "you should see me in a crown", length: 182, album_id: artist1_album1.id, explicit: false, album_order: 4)
artist1_album1_song4_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Billie%20Eilish/WHEN%20WE%20ALL%20FALL%20ASLEEP%2C%20WHERE%20DO%20WE%20GO%3F/04%20you%20should%20see%20me%20in%20a%20crown.mp3")
artist1_album1_song4.track.attach(io: artist1_album1_song4_mp3, filename: '04 you should see me in a crown.mp3')
artist1_album1_song5 = Song.create(title: "all the good girls go to hell", length: 169, album_id: artist1_album1.id, explicit: false, album_order: 5)
artist1_album1_song5_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Billie%20Eilish/WHEN%20WE%20ALL%20FALL%20ASLEEP%2C%20WHERE%20DO%20WE%20GO%3F/05%20all%20the%20good%20girls%20go%20to%20hell.mp3")
artist1_album1_song5.track.attach(io: artist1_album1_song5_mp3, filename: '05 all the good girls go to hell.mp3')
artist1_album1_song6 = Song.create(title: "wish you were gay", length: 222, album_id: artist1_album1.id, explicit: false, album_order: 6)
artist1_album1_song6_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Billie%20Eilish/WHEN%20WE%20ALL%20FALL%20ASLEEP%2C%20WHERE%20DO%20WE%20GO%3F/06%20wish%20you%20were%20gay.mp3")
artist1_album1_song6.track.attach(io: artist1_album1_song6_mp3, filename: '06 wish you were gay.mp3')
artist1_album1_song7 = Song.create(title: "when the party's over", length: 197, album_id: artist1_album1.id, explicit: false, album_order: 7)
artist1_album1_song7_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Billie%20Eilish/WHEN%20WE%20ALL%20FALL%20ASLEEP%2C%20WHERE%20DO%20WE%20GO%3F/07%20when%20the%20party's%20over.mp3")
artist1_album1_song7.track.attach(io: artist1_album1_song7_mp3, filename: '07 when the party\'s over.mp3')
artist1_album1_song8 = Song.create(title: "8", length: 174, album_id: artist1_album1.id, explicit: false, album_order: 8)
artist1_album1_song8_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Billie%20Eilish/WHEN%20WE%20ALL%20FALL%20ASLEEP%2C%20WHERE%20DO%20WE%20GO%3F/08%208.mp3")
artist1_album1_song8.track.attach(io: artist1_album1_song8_mp3, filename: '08 8.mp3')
artist1_album1_song9 = Song.create(title: "my strange addiction", length: 180, album_id: artist1_album1.id, explicit: false, album_order: 9)
artist1_album1_song9_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Billie%20Eilish/WHEN%20WE%20ALL%20FALL%20ASLEEP%2C%20WHERE%20DO%20WE%20GO%3F/09%20my%20strange%20addiction.mp3")
artist1_album1_song9.track.attach(io: artist1_album1_song9_mp3, filename: '09 my strange addiction.mp3')
artist1_album1_song10 = Song.create(title: "bury a friend", length: 194, album_id: artist1_album1.id, explicit: false, album_order: 10)
artist1_album1_song10_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Billie%20Eilish/WHEN%20WE%20ALL%20FALL%20ASLEEP%2C%20WHERE%20DO%20WE%20GO%3F/10%20bury%20a%20friend.mp3")
artist1_album1_song10.track.attach(io: artist1_album1_song10_mp3, filename: '10 bury a friend.mp3')
artist1_album1_song11 = Song.create(title: "ilomilo", length: 157, album_id: artist1_album1.id, explicit: false, album_order: 11)
artist1_album1_song11_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Billie%20Eilish/WHEN%20WE%20ALL%20FALL%20ASLEEP%2C%20WHERE%20DO%20WE%20GO%3F/11%20ilomilo.mp3")
artist1_album1_song11.track.attach(io: artist1_album1_song11_mp3, filename: '11 ilomilo.mp3')
artist1_album1_song12 = Song.create(title: "listen before i go", length: 243, album_id: artist1_album1.id, explicit: false, album_order: 12)
artist1_album1_song12_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Billie%20Eilish/WHEN%20WE%20ALL%20FALL%20ASLEEP%2C%20WHERE%20DO%20WE%20GO%3F/12%20listen%20before%20i%20go.mp3")
artist1_album1_song12.track.attach(io: artist1_album1_song12_mp3, filename: '12 listen before i go.mp3')
artist1_album1_song13 = Song.create(title: "i love you", length: 292, album_id: artist1_album1.id, explicit: false, album_order: 13)
artist1_album1_song13_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Billie%20Eilish/WHEN%20WE%20ALL%20FALL%20ASLEEP%2C%20WHERE%20DO%20WE%20GO%3F/13%20i%20love%20you.mp3")
artist1_album1_song13.track.attach(io: artist1_album1_song13_mp3, filename: '13 i love you.mp3')
artist1_album1_song14 = Song.create(title: "goodbye", length: 120, album_id: artist1_album1.id, explicit: false, album_order: 14)
artist1_album1_song14_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Billie%20Eilish/WHEN%20WE%20ALL%20FALL%20ASLEEP%2C%20WHERE%20DO%20WE%20GO%3F/14%20goodbye.mp3")
artist1_album1_song14.track.attach(io: artist1_album1_song14_mp3, filename: '14 goodbye.mp3')
artist1_album2 = Album.create(title: "dont smile at me", artist_id: artist1.id)
artist1_album2_cover = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Billie%20Eilish/dont%20smile%20at%20me/cover.jpg")
artist1_album2.album_cover.attach(io: artist1_album2_cover, filename: 'cover.jpg')
artist1_album2_song1 = Song.create(title: "Copycat", length: 194, album_id: artist1_album2.id, explicit: false, album_order: 1)
artist1_album2_song1_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Billie%20Eilish/dont%20smile%20at%20me/01%20Copycat.mp3")
artist1_album2_song1.track.attach(io: artist1_album2_song1_mp3, filename: '01 Copycat.mp3')
artist1_album2_song2 = Song.create(title: "IDWBYA", length: 204, album_id: artist1_album2.id, explicit: false, album_order: 2)
artist1_album2_song2_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Billie%20Eilish/dont%20smile%20at%20me/02%20IDWBYA.mp3")
artist1_album2_song2.track.attach(io: artist1_album2_song2_mp3, filename: '02 IDWBYA.mp3')
artist1_album2_song3 = Song.create(title: "My Boy", length: 171, album_id: artist1_album2.id, explicit: false, album_order: 3)
artist1_album2_song3_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Billie%20Eilish/dont%20smile%20at%20me/03%20My%20Boy.mp3")
artist1_album2_song3.track.attach(io: artist1_album2_song3_mp3, filename: '03 My Boy.mp3')
artist1_album2_song4 = Song.create(title: "Watch", length: 178, album_id: artist1_album2.id, explicit: false, album_order: 4)
artist1_album2_song4_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Billie%20Eilish/dont%20smile%20at%20me/04%20Watch.mp3")
artist1_album2_song4.track.attach(io: artist1_album2_song4_mp3, filename: '04 Watch.mp3')
artist1_album2_song5 = Song.create(title: "Party Favor", length: 205, album_id: artist1_album2.id, explicit: false, album_order: 5)
artist1_album2_song5_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Billie%20Eilish/dont%20smile%20at%20me/05%20Party%20Favor.mp3")
artist1_album2_song5.track.attach(io: artist1_album2_song5_mp3, filename: '05 Party Favor.mp3')
artist1_album2_song6 = Song.create(title: "Bellyache", length: 180, album_id: artist1_album2.id, explicit: false, album_order: 6)
artist1_album2_song6_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Billie%20Eilish/dont%20smile%20at%20me/06%20Bellyache.mp3")
artist1_album2_song6.track.attach(io: artist1_album2_song6_mp3, filename: '06 Bellyache.mp3')
artist1_album2_song7 = Song.create(title: "Ocean Eyes", length: 201, album_id: artist1_album2.id, explicit: false, album_order: 7)
artist1_album2_song7_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Billie%20Eilish/dont%20smile%20at%20me/07%20Ocean%20Eyes.mp3")
artist1_album2_song7.track.attach(io: artist1_album2_song7_mp3, filename: '07 Ocean Eyes.mp3')
artist1_album2_song8 = Song.create(title: "Hostage", length: 230, album_id: artist1_album2.id, explicit: false, album_order: 8)
artist1_album2_song8_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Billie%20Eilish/dont%20smile%20at%20me/08%20Hostage.mp3")
artist1_album2_song8.track.attach(io: artist1_album2_song8_mp3, filename: '08 Hostage.mp3')


artist2 = Artist.create(name: 'Jax Jones', has_poster: true)
artist2_hero = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Jax%20Jones/hero.jpg")
artist2.hero_image.attach(io: artist2_hero, filename: 'hero.jpg')
artist2_album1 = Album.create(title: "Snacks", artist_id: artist2.id)
artist2_album1_cover = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Jax%20Jones/Snacks/cover.jpg")
artist2_album1.album_cover.attach(io: artist2_album1_cover, filename: 'cover.jpg')
artist2_album1_song1 = Song.create(title: "Breathe (feat. Ina Wroldsen)", length: 208, album_id: artist2_album1.id, explicit: false, album_order: 1)
artist2_album1_song1_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Jax%20Jones/Snacks/01%20Breathe%20(feat.%20Ina%20Wroldsen).mp3")
artist2_album1_song1.track.attach(io: artist2_album1_song1_mp3, filename: '01 Breathe (feat. Ina Wroldsen).mp3')
artist2_album1_song2 = Song.create(title: "You Don't Know Me (feat. RAYE) [Radio Edit]", length: 212, album_id: artist2_album1.id, explicit: false, album_order: 2)
artist2_album1_song2_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Jax%20Jones/Snacks/02%20You%20Don't%20Know%20Me%20(feat.%20RAYE)%20%5BRadio%20Edit%5D.mp3")
artist2_album1_song2.track.attach(io: artist2_album1_song2_mp3, filename: '02 You Don\'t Know Me (feat. RAYE) [Radio Edit].mp3')
artist2_album1_song3 = Song.create(title: "House Work (feat. Mike Dunn & MNEK)", length: 158, album_id: artist2_album1.id, explicit: false, album_order: 3)
artist2_album1_song3_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Jax%20Jones/Snacks/03%20House%20Work%20(feat.%20Mike%20Dunn%20%26%20MNEK).mp3")
artist2_album1_song3.track.attach(io: artist2_album1_song3_mp3, filename: '03 House Work (feat. Mike Dunn & MNEK).mp3')
artist2_album1_song4 = Song.create(title: "Ring Ring (feat. Rich The Kid)", length: 218, album_id: artist2_album1.id, explicit: false, album_order: 4)
artist2_album1_song4_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Jax%20Jones/Snacks/04%20Ring%20Ring%20(feat.%20Rich%20The%20Kid).mp3")
artist2_album1_song4.track.attach(io: artist2_album1_song4_mp3, filename: '04 Ring Ring (feat. Rich The Kid).mp3')
artist2_album1_song5 = Song.create(title: "Instruction (feat. Demi Lovato & Stefflon Don)", length: 166, album_id: artist2_album1.id, explicit: false, album_order: 5)
artist2_album1_song5_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Jax%20Jones/Snacks/05%20Instruction%20(feat.%20Demi%20Lovato%20%26%20Stefflon%20Don).mp3")
artist2_album1_song5.track.attach(io: artist2_album1_song5_mp3, filename: '05 Instruction (feat. Demi Lovato & Stefflon Don).mp3')


artist3 = Artist.create(name: 'Knife Party', has_poster: true)
artist3_hero = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Knife%20Party/hero.jpg")
artist3.hero_image.attach(io: artist3_hero, filename: 'hero.jpg')
artist3_album1 = Album.create(title: "Abandon Ship", artist_id: artist3.id)
artist3_album1_cover = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Knife%20Party/Abandon%20Ship/cover.jpg")
artist3_album1.album_cover.attach(io: artist3_album1_cover, filename: 'cover.jpg')
artist3_album1_song1 = Song.create(title: "Reconnect", length: 99, album_id: artist3_album1.id, explicit: false, album_order: 1)
artist3_album1_song1_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Knife%20Party/Abandon%20Ship/01%20Reconnect.mp3")
artist3_album1_song1.track.attach(io: artist3_album1_song1_mp3, filename: '01 Reconnect.mp3')
artist3_album1_song2 = Song.create(title: "Resistance", length: 314, album_id: artist3_album1.id, explicit: false, album_order: 2)
artist3_album1_song2_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Knife%20Party/Abandon%20Ship/02%20Resistance.mp3")
artist3_album1_song2.track.attach(io: artist3_album1_song2_mp3, filename: '02 Resistance.mp3')
artist3_album1_song3 = Song.create(title: "Boss Mode", length: 228, album_id: artist3_album1.id, explicit: false, album_order: 3)
artist3_album1_song3_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Knife%20Party/Abandon%20Ship/03%20Boss%20Mode.mp3")
artist3_album1_song3.track.attach(io: artist3_album1_song3_mp3, filename: '03 Boss Mode.mp3')
artist3_album1_song4 = Song.create(title: "EDM Trend Machine", length: 306, album_id: artist3_album1.id, explicit: false, album_order: 4)
artist3_album1_song4_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Knife%20Party/Abandon%20Ship/04%20EDM%20Trend%20Machine.mp3")
artist3_album1_song4.track.attach(io: artist3_album1_song4_mp3, filename: '04 EDM Trend Machine.mp3')
artist3_album1_song5 = Song.create(title: "404", length: 299, album_id: artist3_album1.id, explicit: false, album_order: 5)
artist3_album1_song5_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Knife%20Party/Abandon%20Ship/05%20404.mp3")
artist3_album1_song5.track.attach(io: artist3_album1_song5_mp3, filename: '05 404.mp3')
artist3_album1_song6 = Song.create(title: "Begin Again", length: 356, album_id: artist3_album1.id, explicit: false, album_order: 6)
artist3_album1_song6_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Knife%20Party/Abandon%20Ship/06%20Begin%20Again.mp3")
artist3_album1_song6.track.attach(io: artist3_album1_song6_mp3, filename: '06 Begin Again.mp3')
artist3_album1_song7 = Song.create(title: "Give It Up", length: 252, album_id: artist3_album1.id, explicit: false, album_order: 7)
artist3_album1_song7_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Knife%20Party/Abandon%20Ship/07%20Give%20It%20Up.mp3")
artist3_album1_song7.track.attach(io: artist3_album1_song7_mp3, filename: '07 Give It Up.mp3')
artist3_album1_song8 = Song.create(title: "D.I.M.H", length: 347, album_id: artist3_album1.id, explicit: false, album_order: 8)
artist3_album1_song8_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Knife%20Party/Abandon%20Ship/08.%20D.I.M.H.mp3")
artist3_album1_song8.track.attach(io: artist3_album1_song8_mp3, filename: '08. D.I.M.H.mp3')
artist3_album1_song9 = Song.create(title: "Micropenis", length: 333, album_id: artist3_album1.id, explicit: false, album_order: 9)
artist3_album1_song9_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Knife%20Party/Abandon%20Ship/09%20Micropenis.mp3")
artist3_album1_song9.track.attach(io: artist3_album1_song9_mp3, filename: '09 Micropenis.mp3')
artist3_album1_song10 = Song.create(title: "Superstar", length: 256, album_id: artist3_album1.id, explicit: false, album_order: 10)
artist3_album1_song10_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Knife%20Party/Abandon%20Ship/10%20Superstar.mp3")
artist3_album1_song10.track.attach(io: artist3_album1_song10_mp3, filename: '10 Superstar.mp3')
artist3_album1_song11 = Song.create(title: "Red Dawn", length: 368, album_id: artist3_album1.id, explicit: false, album_order: 11)
artist3_album1_song11_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Knife%20Party/Abandon%20Ship/11%20Red%20Dawn.mp3")
artist3_album1_song11.track.attach(io: artist3_album1_song11_mp3, filename: '11 Red Dawn.mp3')
artist3_album1_song12 = Song.create(title: "Kaleidoscope", length: 241, album_id: artist3_album1.id, explicit: false, album_order: 12)
artist3_album1_song12_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Knife%20Party/Abandon%20Ship/12%20Kaleidoscope.mp3")
artist3_album1_song12.track.attach(io: artist3_album1_song12_mp3, filename: '12 Kaleidoscope.mp3')


artist4 = Artist.create(name: 'ODESZA', has_poster: true)
artist4_hero = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/ODESZA/hero.jpg")
artist4.hero_image.attach(io: artist4_hero, filename: 'hero.jpg')
artist4_album1 = Album.create(title: "A Moment Apart", artist_id: artist4.id)
artist4_album1_cover = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/ODESZA/A%20Moment%20Apart/cover.jpg")
artist4_album1.album_cover.attach(io: artist4_album1_cover, filename: 'cover.jpg')
artist4_album1_song1 = Song.create(title: "Intro", length: 65, album_id: artist4_album1.id, explicit: false, album_order: 1)
artist4_album1_song1_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/ODESZA/A%20Moment%20Apart/1%20Intro.mp3")
artist4_album1_song1.track.attach(io: artist4_album1_song1_mp3, filename: '1 Intro.mp3')
artist4_album1_song2 = Song.create(title: "A Moment Apart", length: 235, album_id: artist4_album1.id, explicit: false, album_order: 2)
artist4_album1_song2_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/ODESZA/A%20Moment%20Apart/2%20A%20Moment%20Apart.mp3")
artist4_album1_song2.track.attach(io: artist4_album1_song2_mp3, filename: '2 A Moment Apart.mp3')
artist4_album1_song3 = Song.create(title: "Higher Ground (feat. Naomi Wild)", length: 216, album_id: artist4_album1.id, explicit: false, album_order: 3)
artist4_album1_song3_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/ODESZA/A%20Moment%20Apart/3%20Higher%20Ground%20(feat.%20Naomi%20Wild).mp3")
artist4_album1_song3.track.attach(io: artist4_album1_song3_mp3, filename: '3 Higher Ground (feat. Naomi Wild).mp3')
artist4_album1_song4 = Song.create(title: "Boy", length: 184, album_id: artist4_album1.id, explicit: false, album_order: 4)
artist4_album1_song4_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/ODESZA/A%20Moment%20Apart/4%20Boy.mp3")
artist4_album1_song4.track.attach(io: artist4_album1_song4_mp3, filename: '4 Boy.mp3')
artist4_album1_song5 = Song.create(title: "Line of Sight (feat. WYNNE & Mansionair)", length: 237, album_id: artist4_album1.id, explicit: false, album_order: 5)
artist4_album1_song5_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/ODESZA/A%20Moment%20Apart/5%20Line%20of%20Sight%20(feat.%20WYNNE%20%26%20Mansionair).mp3")
artist4_album1_song5.track.attach(io: artist4_album1_song5_mp3, filename: '5 Line of Sight (feat. WYNNE & Mansionair).mp3')
artist4_album1_song6 = Song.create(title: "Late Night", length: 229, album_id: artist4_album1.id, explicit: false, album_order: 6)
artist4_album1_song6_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/ODESZA/A%20Moment%20Apart/6%20Late%20Night.mp3")
artist4_album1_song6.track.attach(io: artist4_album1_song6_mp3, filename: '6 Late Night.mp3')
artist4_album1_song7 = Song.create(title: "Across the Room (feat. Leon Bridges)", length: 284, album_id: artist4_album1.id, explicit: false, album_order: 7)
artist4_album1_song7_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/ODESZA/A%20Moment%20Apart/7%20Across%20the%20Room%20(feat.%20Leon%20Bridges).mp3")
artist4_album1_song7.track.attach(io: artist4_album1_song7_mp3, filename: '7 Across the Room (feat. Leon Bridges).mp3')
artist4_album1_song8 = Song.create(title: "Meridian", length: 236, album_id: artist4_album1.id, explicit: false, album_order: 8)
artist4_album1_song8_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/ODESZA/A%20Moment%20Apart/8%20Meridian.mp3")
artist4_album1_song8.track.attach(io: artist4_album1_song8_mp3, filename: '8 Meridian.mp3')
artist4_album1_song9 = Song.create(title: "Everything At Your Feet (feat. The Chamanas)", length: 209, album_id: artist4_album1.id, explicit: false, album_order: 9)
artist4_album1_song9_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/ODESZA/A%20Moment%20Apart/9%20Everything%20At%20Your%20Feet%20(feat.%20The%20Chamanas).mp3")
artist4_album1_song9.track.attach(io: artist4_album1_song9_mp3, filename: '9 Everything At Your Feet (feat. The Chamanas).mp3')
artist4_album1_song10 = Song.create(title: "Just A Memory (feat. Regina Spektor)", length: 237, album_id: artist4_album1.id, explicit: false, album_order: 10)
artist4_album1_song10_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/ODESZA/A%20Moment%20Apart/10%20Just%20A%20Memory%20(feat.%20Regina%20Spektor).mp3")
artist4_album1_song10.track.attach(io: artist4_album1_song10_mp3, filename: '10 Just A Memory (feat. Regina Spektor).mp3')
artist4_album1_song11 = Song.create(title: "Divide (feat. Kelsey Bulkin)", length: 242, album_id: artist4_album1.id, explicit: false, album_order: 11)
artist4_album1_song11_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/ODESZA/A%20Moment%20Apart/11%20Divide%20(feat.%20Kelsey%20Bulkin).mp3")
artist4_album1_song11.track.attach(io: artist4_album1_song11_mp3, filename: '11 Divide (feat. Kelsey Bulkin).mp3')
artist4_album1_song12 = Song.create(title: "Thin Floors and Tall Ceilings", length: 179, album_id: artist4_album1.id, explicit: false, album_order: 12)
artist4_album1_song12_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/ODESZA/A%20Moment%20Apart/12%20Thin%20Floors%20and%20Tall%20Ceilings.mp3")
artist4_album1_song12.track.attach(io: artist4_album1_song12_mp3, filename: '12 Thin Floors and Tall Ceilings.mp3')
artist4_album1_song13 = Song.create(title: "La Ciudad", length: 272, album_id: artist4_album1.id, explicit: false, album_order: 13)
artist4_album1_song13_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/ODESZA/A%20Moment%20Apart/13%20La%20Ciudad.mp3")
artist4_album1_song13.track.attach(io: artist4_album1_song13_mp3, filename: '13 La Ciudad.mp3')
artist4_album1_song14 = Song.create(title: "Falls (feat. Sasha Sloan)", length: 234, album_id: artist4_album1.id, explicit: false, album_order: 14)
artist4_album1_song14_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/ODESZA/A%20Moment%20Apart/14%20Falls%20(feat.%20Sasha%20Sloan).mp3")
artist4_album1_song14.track.attach(io: artist4_album1_song14_mp3, filename: '14 Falls (feat. Sasha Sloan).mp3')
artist4_album1_song15 = Song.create(title: "Show Me", length: 219, album_id: artist4_album1.id, explicit: false, album_order: 15)
artist4_album1_song15_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/ODESZA/A%20Moment%20Apart/15%20Show%20Me.mp3")
artist4_album1_song15.track.attach(io: artist4_album1_song15_mp3, filename: '15 Show Me.mp3')
artist4_album1_song16 = Song.create(title: "Corners of the Earth (feat. RY X)", length: 306, album_id: artist4_album1.id, explicit: false, album_order: 16)
artist4_album1_song16_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/ODESZA/A%20Moment%20Apart/16%20Corners%20of%20the%20Earth%20(feat.%20RY%20X).mp3")
artist4_album1_song16.track.attach(io: artist4_album1_song16_mp3, filename: '16 Corners of the Earth (feat. RY X).mp3')
artist4_album2 = Album.create(title: "In Return", artist_id: artist4.id)
artist4_album2_cover = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/ODESZA/In%20Return/cover.jpg")
artist4_album2.album_cover.attach(io: artist4_album2_cover, filename: 'cover.jpg')
artist4_album2_song1 = Song.create(title: "Always This Late", length: 162, album_id: artist4_album2.id, explicit: false, album_order: 1)
artist4_album2_song1_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/ODESZA/In%20Return/01%20Always%20This%20Late.mp3")
artist4_album2_song1.track.attach(io: artist4_album2_song1_mp3, filename: '01 Always This Late.mp3')
artist4_album2_song2 = Song.create(title: "Say My Name (feat. Zyra)", length: 264, album_id: artist4_album2.id, explicit: false, album_order: 2)
artist4_album2_song2_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/ODESZA/In%20Return/02%20Say%20My%20Name%20(feat.%20Zyra).mp3")
artist4_album2_song2.track.attach(io: artist4_album2_song2_mp3, filename: '02 Say My Name (feat. Zyra).mp3')
artist4_album2_song3 = Song.create(title: "Bloom", length: 196, album_id: artist4_album2.id, explicit: false, album_order: 3)
artist4_album2_song3_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/ODESZA/In%20Return/03%20Bloom.mp3")
artist4_album2_song3.track.attach(io: artist4_album2_song3_mp3, filename: '03 Bloom.mp3')
artist4_album2_song4 = Song.create(title: "All We Need (feat. Shy Girls)", length: 212, album_id: artist4_album2.id, explicit: false, album_order: 4)
artist4_album2_song4_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/ODESZA/In%20Return/04%20All%20We%20Need%20(feat.%20Shy%20Girls).mp3")
artist4_album2_song4.track.attach(io: artist4_album2_song4_mp3, filename: '04 All We Need (feat. Shy Girls).mp3')
artist4_album2_song5 = Song.create(title: "Sundara", length: 137, album_id: artist4_album2.id, explicit: false, album_order: 5)
artist4_album2_song5_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/ODESZA/In%20Return/05%20Sundara.mp3")
artist4_album2_song5.track.attach(io: artist4_album2_song5_mp3, filename: '05 Sundara.mp3')
artist4_album2_song6 = Song.create(title: "White Lies (feat. Jenni Potts)", length: 278, album_id: artist4_album2.id, explicit: false, album_order: 6)
artist4_album2_song6_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/ODESZA/In%20Return/06%20White%20Lies%20(feat.%20Jenni%20Potts).mp3")
artist4_album2_song6.track.attach(io: artist4_album2_song6_mp3, filename: '06 White Lies (feat. Jenni Potts).mp3')
artist4_album2_song7 = Song.create(title: "Kusanagi", length: 209, album_id: artist4_album2.id, explicit: false, album_order: 7)
artist4_album2_song7_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/ODESZA/In%20Return/07%20Kusanagi.mp3")
artist4_album2_song7.track.attach(io: artist4_album2_song7_mp3, filename: '07 Kusanagi.mp3')
artist4_album2_song8 = Song.create(title: "Echoes (feat. Py)", length: 265, album_id: artist4_album2.id, explicit: false, album_order: 8)
artist4_album2_song8_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/ODESZA/In%20Return/08%20Echoes%20(feat.%20Py).mp3")
artist4_album2_song8.track.attach(io: artist4_album2_song8_mp3, filename: '08 Echoes (feat. Py).mp3')
artist4_album2_song9 = Song.create(title: "It's Only (feat. Zyra)", length: 269, album_id: artist4_album2.id, explicit: false, album_order: 9)
artist4_album2_song9_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/ODESZA/In%20Return/09%20It's%20Only%20(feat.%20Zyra).mp3")
artist4_album2_song9.track.attach(io: artist4_album2_song9_mp3, filename: '09 It\'s Only (feat. Zyra).mp3')
artist4_album2_song10 = Song.create(title: "Koto", length: 195, album_id: artist4_album2.id, explicit: false, album_order: 10)
artist4_album2_song10_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/ODESZA/In%20Return/10%20Koto.mp3")
artist4_album2_song10.track.attach(io: artist4_album2_song10_mp3, filename: '10 Koto.mp3')
artist4_album2_song11 = Song.create(title: "Memories That You Call (feat. Monsoonsiren)", length: 249, album_id: artist4_album2.id, explicit: false, album_order: 11)
artist4_album2_song11_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/ODESZA/In%20Return/11%20Memories%20That%20You%20Call%20(feat.%20Monsoonsiren).mp3")
artist4_album2_song11.track.attach(io: artist4_album2_song11_mp3, filename: '11 Memories That You Call (feat. Monsoonsiren).mp3')
artist4_album2_song12 = Song.create(title: "Sun Models (feat. Madelyn Grant)", length: 161, album_id: artist4_album2.id, explicit: false, album_order: 12)
artist4_album2_song12_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/ODESZA/In%20Return/12%20Sun%20Models%20(feat.%20Madelyn%20Grant).mp3")
artist4_album2_song12.track.attach(io: artist4_album2_song12_mp3, filename: '12 Sun Models (feat. Madelyn Grant).mp3')
artist4_album2_song13 = Song.create(title: "For Us (feat. Briana Marela)", length: 352, album_id: artist4_album2.id, explicit: false, album_order: 13)
artist4_album2_song13_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/ODESZA/In%20Return/13%20For%20Us%20(feat.%20Briana%20Marela).mp3")
artist4_album2_song13.track.attach(io: artist4_album2_song13_mp3, filename: '13 For Us (feat. Briana Marela).mp3')


artist5 = Artist.create(name: 'Post Malone', has_poster: true)
artist5_hero = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Post%20Malone/hero.jpg")
artist5.hero_image.attach(io: artist5_hero, filename: 'hero.jpg')
artist5_album1 = Album.create(title: "Stoney", artist_id: artist5.id)
artist5_album1_cover = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Post%20Malone/Stoney/cover.jpg")
artist5_album1.album_cover.attach(io: artist5_album1_cover, filename: 'cover.jpg')
artist5_album1_song1 = Song.create(title: "Broken Whiskey Glass", length: 234, album_id: artist5_album1.id, explicit: false, album_order: 1)
artist5_album1_song1_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Post%20Malone/Stoney/1%20Broken%20Whiskey%20Glass.mp3")
artist5_album1_song1.track.attach(io: artist5_album1_song1_mp3, filename: '1 Broken Whiskey Glass.mp3')
artist5_album1_song2 = Song.create(title: "Big Lie", length: 208, album_id: artist5_album1.id, explicit: false, album_order: 2)
artist5_album1_song2_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Post%20Malone/Stoney/2%20Big%20Lie.mp3")
artist5_album1_song2.track.attach(io: artist5_album1_song2_mp3, filename: '2 Big Lie.mp3')
artist5_album1_song3 = Song.create(title: "Deja Vu feat. Justin Bieber", length: 235, album_id: artist5_album1.id, explicit: false, album_order: 3)
artist5_album1_song3_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Post%20Malone/Stoney/3%20Deja%20Vu%20feat.%20Justin%20Bieber.mp3")
artist5_album1_song3.track.attach(io: artist5_album1_song3_mp3, filename: '3 Deja Vu feat. Justin Bieber.mp3')
artist5_album1_song4 = Song.create(title: "No Option", length: 180, album_id: artist5_album1.id, explicit: false, album_order: 4)
artist5_album1_song4_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Post%20Malone/Stoney/4%20No%20Option.mp3")
artist5_album1_song4.track.attach(io: artist5_album1_song4_mp3, filename: '4 No Option.mp3')
artist5_album1_song5 = Song.create(title: "Cold", length: 269, album_id: artist5_album1.id, explicit: false, album_order: 5)
artist5_album1_song5_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Post%20Malone/Stoney/5%20Cold.mp3")
artist5_album1_song5.track.attach(io: artist5_album1_song5_mp3, filename: '5 Cold.mp3')
artist5_album1_song6 = Song.create(title: "White Iverson", length: 257, album_id: artist5_album1.id, explicit: false, album_order: 6)
artist5_album1_song6_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Post%20Malone/Stoney/6%20White%20Iverson.mp3")
artist5_album1_song6.track.attach(io: artist5_album1_song6_mp3, filename: '6 White Iverson.mp3')
artist5_album1_song7 = Song.create(title: "I Fall Apart", length: 224, album_id: artist5_album1.id, explicit: false, album_order: 7)
artist5_album1_song7_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Post%20Malone/Stoney/7%20I%20Fall%20Apart.mp3")
artist5_album1_song7.track.attach(io: artist5_album1_song7_mp3, filename: '7 I Fall Apart.mp3')
artist5_album1_song8 = Song.create(title: "Patient", length: 195, album_id: artist5_album1.id, explicit: false, album_order: 8)
artist5_album1_song8_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Post%20Malone/Stoney/8%20Patient.mp3")
artist5_album1_song8.track.attach(io: artist5_album1_song8_mp3, filename: '8 Patient.mp3')
artist5_album1_song9 = Song.create(title: "Go Flex", length: 180, album_id: artist5_album1.id, explicit: false, album_order: 9)
artist5_album1_song9_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Post%20Malone/Stoney/9%20Go%20Flex.mp3")
artist5_album1_song9.track.attach(io: artist5_album1_song9_mp3, filename: '9 Go Flex.mp3')
artist5_album1_song10 = Song.create(title: "Feel (feat. Kehlani)", length: 198, album_id: artist5_album1.id, explicit: false, album_order: 10)
artist5_album1_song10_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Post%20Malone/Stoney/10%20Feel%20(feat.%20Kehlani).mp3")
artist5_album1_song10.track.attach(io: artist5_album1_song10_mp3, filename: '10 Feel (feat. Kehlani).mp3')
artist5_album1_song11 = Song.create(title: "Too Young", length: 238, album_id: artist5_album1.id, explicit: false, album_order: 11)
artist5_album1_song11_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Post%20Malone/Stoney/11%20Too%20Young.mp3")
artist5_album1_song11.track.attach(io: artist5_album1_song11_mp3, filename: '11 Too Young.mp3')
artist5_album1_song12 = Song.create(title: "Congratulations feat. Quavo", length: 221, album_id: artist5_album1.id, explicit: false, album_order: 12)
artist5_album1_song12_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Post%20Malone/Stoney/12%20Congratulations%20feat.%20Quavo.mp3")
artist5_album1_song12.track.attach(io: artist5_album1_song12_mp3, filename: '12 Congratulations feat. Quavo.mp3')
artist5_album1_song13 = Song.create(title: "Up There", length: 195, album_id: artist5_album1.id, explicit: false, album_order: 13)
artist5_album1_song13_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Post%20Malone/Stoney/13%20Up%20There.mp3")
artist5_album1_song13.track.attach(io: artist5_album1_song13_mp3, filename: '13 Up There.mp3')
artist5_album1_song14 = Song.create(title: "Yours Truly, Austin Post", length: 220, album_id: artist5_album1.id, explicit: false, album_order: 14)
artist5_album1_song14_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Post%20Malone/Stoney/14%20Yours%20Truly%2C%20Austin%20Post.mp3")
artist5_album1_song14.track.attach(io: artist5_album1_song14_mp3, filename: '14 Yours Truly, Austin Post.mp3')
artist5_album1_song15 = Song.create(title: "Leave", length: 325, album_id: artist5_album1.id, explicit: false, album_order: 15)
artist5_album1_song15_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Post%20Malone/Stoney/15%20Leave.mp3")
artist5_album1_song15.track.attach(io: artist5_album1_song15_mp3, filename: '15 Leave.mp3')
artist5_album1_song16 = Song.create(title: "Hit This Hard", length: 250, album_id: artist5_album1.id, explicit: false, album_order: 16)
artist5_album1_song16_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Post%20Malone/Stoney/16%20Hit%20This%20Hard.mp3")
artist5_album1_song16.track.attach(io: artist5_album1_song16_mp3, filename: '16 Hit This Hard.mp3')
artist5_album1_song17 = Song.create(title: "Money Made Me Do It (feat. 2 Chainz)", length: 225, album_id: artist5_album1.id, explicit: false, album_order: 17)
artist5_album1_song17_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Post%20Malone/Stoney/17%20Money%20Made%20Me%20Do%20It%20(feat.%202%20Chainz).mp3")
artist5_album1_song17.track.attach(io: artist5_album1_song17_mp3, filename: '17 Money Made Me Do It (feat. 2 Chainz).mp3')
artist5_album1_song18 = Song.create(title: "Feeling Whitney", length: 258, album_id: artist5_album1.id, explicit: false, album_order: 18)
artist5_album1_song18_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Post%20Malone/Stoney/18%20Feeling%20Whitney.mp3")
artist5_album1_song18.track.attach(io: artist5_album1_song18_mp3, filename: '18 Feeling Whitney.mp3')
artist5_album2 = Album.create(title: "beerbongs & bentleys", artist_id: artist5.id)
artist5_album2_cover = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Post%20Malone/beerbongs%20%26%20bentleys/cover.jpg")
artist5_album2.album_cover.attach(io: artist5_album2_cover, filename: 'cover.jpg')
artist5_album2_song1 = Song.create(title: "Paranoid", length: 222, album_id: artist5_album2.id, explicit: false, album_order: 1)
artist5_album2_song1_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Post%20Malone/beerbongs%20%26%20bentleys/01%20Paranoid.mp3")
artist5_album2_song1.track.attach(io: artist5_album2_song1_mp3, filename: '01 Paranoid.mp3')
artist5_album2_song2 = Song.create(title: "Spoil My Night (feat. Swae Lee)", length: 195, album_id: artist5_album2.id, explicit: false, album_order: 2)
artist5_album2_song2_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Post%20Malone/beerbongs%20%26%20bentleys/02%20Spoil%20My%20Night%20(feat.%20Swae%20Lee).mp3")
artist5_album2_song2.track.attach(io: artist5_album2_song2_mp3, filename: '02 Spoil My Night (feat. Swae Lee).mp3')
artist5_album2_song3 = Song.create(title: "Rich & Sad", length: 207, album_id: artist5_album2.id, explicit: false, album_order: 3)
artist5_album2_song3_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Post%20Malone/beerbongs%20%26%20bentleys/03%20Rich%20%26%20Sad.mp3")
artist5_album2_song3.track.attach(io: artist5_album2_song3_mp3, filename: '03 Rich & Sad.mp3')
artist5_album2_song4 = Song.create(title: "Zack and Codeine", length: 205, album_id: artist5_album2.id, explicit: false, album_order: 4)
artist5_album2_song4_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Post%20Malone/beerbongs%20%26%20bentleys/04%20Zack%20and%20Codeine.mp3")
artist5_album2_song4.track.attach(io: artist5_album2_song4_mp3, filename: '04 Zack and Codeine.mp3')
artist5_album2_song5 = Song.create(title: "Takin' Shots", length: 217, album_id: artist5_album2.id, explicit: false, album_order: 5)
artist5_album2_song5_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Post%20Malone/beerbongs%20%26%20bentleys/05%20Takin'%20Shots.mp3")
artist5_album2_song5.track.attach(io: artist5_album2_song5_mp3, filename: '05 Takin\' Shots.mp3')
artist5_album2_song6 = Song.create(title: "rockstar (feat. 21 Savage)", length: 219, album_id: artist5_album2.id, explicit: false, album_order: 6)
artist5_album2_song6_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Post%20Malone/beerbongs%20%26%20bentleys/06%20rockstar%20(feat.%2021%20Savage).mp3")
artist5_album2_song6.track.attach(io: artist5_album2_song6_mp3, filename: '06 rockstar (feat. 21 Savage).mp3')
artist5_album2_song7 = Song.create(title: "Over Now", length: 248, album_id: artist5_album2.id, explicit: false, album_order: 7)
artist5_album2_song7_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Post%20Malone/beerbongs%20%26%20bentleys/07%20Over%20Now.mp3")
artist5_album2_song7.track.attach(io: artist5_album2_song7_mp3, filename: '07 Over Now.mp3')
artist5_album2_song8 = Song.create(title: "Psycho (feat. Ty Dolla $ign)", length: 222, album_id: artist5_album2.id, explicit: false, album_order: 8)
artist5_album2_song8_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Post%20Malone/beerbongs%20%26%20bentleys/08%20Psycho%20(feat.%20Ty%20Dolla%20%24ign).mp3")
artist5_album2_song8.track.attach(io: artist5_album2_song8_mp3, filename: '08 Psycho (feat. Ty Dolla $ign).mp3')
artist5_album2_song9 = Song.create(title: "Better Now", length: 232, album_id: artist5_album2.id, explicit: false, album_order: 9)
artist5_album2_song9_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Post%20Malone/beerbongs%20%26%20bentleys/09%20Better%20Now.mp3")
artist5_album2_song9.track.attach(io: artist5_album2_song9_mp3, filename: '09 Better Now.mp3')
artist5_album2_song10 = Song.create(title: "Ball For Me (feat. Nicki Minaj)", length: 207, album_id: artist5_album2.id, explicit: false, album_order: 10)
artist5_album2_song10_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Post%20Malone/beerbongs%20%26%20bentleys/10%20Ball%20For%20Me%20(feat.%20Nicki%20Minaj).mp3")
artist5_album2_song10.track.attach(io: artist5_album2_song10_mp3, filename: '10 Ball For Me (feat. Nicki Minaj).mp3')
artist5_album2_song11 = Song.create(title: "Otherside", length: 229, album_id: artist5_album2.id, explicit: false, album_order: 11)
artist5_album2_song11_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Post%20Malone/beerbongs%20%26%20bentleys/11%20Otherside.mp3")
artist5_album2_song11.track.attach(io: artist5_album2_song11_mp3, filename: '11 Otherside.mp3')
artist5_album2_song12 = Song.create(title: "Stay", length: 205, album_id: artist5_album2.id, explicit: false, album_order: 12)
artist5_album2_song12_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Post%20Malone/beerbongs%20%26%20bentleys/12%20Stay.mp3")
artist5_album2_song12.track.attach(io: artist5_album2_song12_mp3, filename: '12 Stay.mp3')
artist5_album2_song13 = Song.create(title: "Blame It On Me", length: 262, album_id: artist5_album2.id, explicit: false, album_order: 13)
artist5_album2_song13_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Post%20Malone/beerbongs%20%26%20bentleys/13%20Blame%20It%20On%20Me.mp3")
artist5_album2_song13.track.attach(io: artist5_album2_song13_mp3, filename: '13 Blame It On Me.mp3')
artist5_album2_song14 = Song.create(title: "Same Bitches (feat. G-Eazy & YG)", length: 213, album_id: artist5_album2.id, explicit: false, album_order: 14)
artist5_album2_song14_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Post%20Malone/beerbongs%20%26%20bentleys/14%20Same%20Bitches%20(feat.%20G-Eazy%20%26%20YG).mp3")
artist5_album2_song14.track.attach(io: artist5_album2_song14_mp3, filename: '14 Same Bitches (feat. G-Eazy & YG).mp3')
artist5_album2_song15 = Song.create(title: "Jonestown (Interlude)", length: 113, album_id: artist5_album2.id, explicit: false, album_order: 15)
artist5_album2_song15_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Post%20Malone/beerbongs%20%26%20bentleys/15%20Jonestown%20(Interlude).mp3")
artist5_album2_song15.track.attach(io: artist5_album2_song15_mp3, filename: '15 Jonestown (Interlude).mp3')
artist5_album2_song16 = Song.create(title: "92 Explorer", length: 212, album_id: artist5_album2.id, explicit: false, album_order: 16)
artist5_album2_song16_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Post%20Malone/beerbongs%20%26%20bentleys/16%2092%20Explorer.mp3")
artist5_album2_song16.track.attach(io: artist5_album2_song16_mp3, filename: '16 92 Explorer.mp3')
artist5_album2_song17 = Song.create(title: "Candy Paint", length: 228, album_id: artist5_album2.id, explicit: false, album_order: 17)
artist5_album2_song17_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Post%20Malone/beerbongs%20%26%20bentleys/17%20Candy%20Paint.mp3")
artist5_album2_song17.track.attach(io: artist5_album2_song17_mp3, filename: '17 Candy Paint.mp3')
artist5_album2_song18 = Song.create(title: "Sugar Wraith", length: 229, album_id: artist5_album2.id, explicit: false, album_order: 18)
artist5_album2_song18_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/Post%20Malone/beerbongs%20%26%20bentleys/18%20Sugar%20Wraith.mp3")
artist5_album2_song18.track.attach(io: artist5_album2_song18_mp3, filename: '18 Sugar Wraith.mp3')


artist6 = Artist.create(name: 'REZZ', has_poster: true)
artist6_hero = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/REZZ/hero.jpg")
artist6.hero_image.attach(io: artist6_hero, filename: 'hero.jpg')
artist6_album1 = Album.create(title: "Mass Manipulation", artist_id: artist6.id)
artist6_album1_cover = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/REZZ/Mass%20Manipulation/cover.jpg")
artist6_album1.album_cover.attach(io: artist6_album1_cover, filename: 'cover.jpg')
artist6_album1_song1 = Song.create(title: "Relax", length: 215, album_id: artist6_album1.id, explicit: false, album_order: 1)
artist6_album1_song1_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/REZZ/Mass%20Manipulation/01%20Relax.mp3")
artist6_album1_song1.track.attach(io: artist6_album1_song1_mp3, filename: '01 Relax.mp3')
artist6_album1_song2 = Song.create(title: "Diluted Brains", length: 248, album_id: artist6_album1.id, explicit: false, album_order: 2)
artist6_album1_song2_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/REZZ/Mass%20Manipulation/02%20Diluted%20Brains.mp3")
artist6_album1_song2.track.attach(io: artist6_album1_song2_mp3, filename: '02 Diluted Brains.mp3')
artist6_album1_song3 = Song.create(title: "Premonition", length: 275, album_id: artist6_album1.id, explicit: false, album_order: 3)
artist6_album1_song3_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/REZZ/Mass%20Manipulation/03%20Premonition.mp3")
artist6_album1_song3.track.attach(io: artist6_album1_song3_mp3, filename: '03 Premonition.mp3')
artist6_album1_song4 = Song.create(title: "DRUGS", length: 198, album_id: artist6_album1.id, explicit: false, album_order: 4)
artist6_album1_song4_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/REZZ/Mass%20Manipulation/04%20DRUGS.mp3")
artist6_album1_song4.track.attach(io: artist6_album1_song4_mp3, filename: '04 DRUGS.mp3')
artist6_album1_song5 = Song.create(title: "LIVID", length: 193, album_id: artist6_album1.id, explicit: false, album_order: 5)
artist6_album1_song5_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/REZZ/Mass%20Manipulation/05%20LIVID.mp3")
artist6_album1_song5.track.attach(io: artist6_album1_song5_mp3, filename: '05 LIVID.mp3')
artist6_album1_song6 = Song.create(title: "Green Gusher", length: 178, album_id: artist6_album1.id, explicit: false, album_order: 6)
artist6_album1_song6_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/REZZ/Mass%20Manipulation/06%20Green%20Gusher.mp3")
artist6_album1_song6.track.attach(io: artist6_album1_song6_mp3, filename: '06 Green Gusher.mp3')
artist6_album1_song7 = Song.create(title: "Synesthesia", length: 190, album_id: artist6_album1.id, explicit: false, album_order: 7)
artist6_album1_song7_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/REZZ/Mass%20Manipulation/07%20Synesthesia.mp3")
artist6_album1_song7.track.attach(io: artist6_album1_song7_mp3, filename: '07 Synesthesia.mp3')
artist6_album1_song8 = Song.create(title: "Ascension", length: 209, album_id: artist6_album1.id, explicit: false, album_order: 8)
artist6_album1_song8_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/REZZ/Mass%20Manipulation/08%20Ascension.mp3")
artist6_album1_song8.track.attach(io: artist6_album1_song8_mp3, filename: '08 Ascension.mp3')


artist7 = Artist.create(name: 'The XX', has_poster: true)
artist7_hero = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/The%20XX/hero.jpg")
artist7.hero_image.attach(io: artist7_hero, filename: 'hero.jpg')
artist7_album1 = Album.create(title: "xx", artist_id: artist7.id)
artist7_album1_cover = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/The%20XX/xx/cover.jpg")
artist7_album1.album_cover.attach(io: artist7_album1_cover, filename: 'cover.jpg')
artist7_album1_song1 = Song.create(title: "Intro", length: 128, album_id: artist7_album1.id, explicit: false, album_order: 1)
artist7_album1_song1_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/The%20XX/xx/01%20Intro.mp3")
artist7_album1_song1.track.attach(io: artist7_album1_song1_mp3, filename: '01 Intro.mp3')
artist7_album1_song2 = Song.create(title: "Vcr", length: 178, album_id: artist7_album1.id, explicit: false, album_order: 2)
artist7_album1_song2_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/The%20XX/xx/02%20Vcr.mp3")
artist7_album1_song2.track.attach(io: artist7_album1_song2_mp3, filename: '02 Vcr.mp3')
artist7_album1_song3 = Song.create(title: "Crystalised", length: 203, album_id: artist7_album1.id, explicit: false, album_order: 3)
artist7_album1_song3_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/The%20XX/xx/03%20Crystalised.mp3")
artist7_album1_song3.track.attach(io: artist7_album1_song3_mp3, filename: '03 Crystalised.mp3')
artist7_album1_song4 = Song.create(title: "Islands", length: 161, album_id: artist7_album1.id, explicit: false, album_order: 4)
artist7_album1_song4_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/The%20XX/xx/04%20Islands.mp3")
artist7_album1_song4.track.attach(io: artist7_album1_song4_mp3, filename: '04 Islands.mp3')
artist7_album1_song5 = Song.create(title: "Heart Skipped A Beat", length: 243, album_id: artist7_album1.id, explicit: false, album_order: 5)
artist7_album1_song5_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/The%20XX/xx/05%20Heart%20Skipped%20A%20Beat.mp3")
artist7_album1_song5.track.attach(io: artist7_album1_song5_mp3, filename: '05 Heart Skipped A Beat.mp3')
artist7_album1_song6 = Song.create(title: "Fantasy", length: 159, album_id: artist7_album1.id, explicit: false, album_order: 6)
artist7_album1_song6_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/The%20XX/xx/06%20Fantasy.mp3")
artist7_album1_song6.track.attach(io: artist7_album1_song6_mp3, filename: '06 Fantasy.mp3')
artist7_album1_song7 = Song.create(title: "Shelter", length: 271, album_id: artist7_album1.id, explicit: false, album_order: 7)
artist7_album1_song7_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/The%20XX/xx/07%20Shelter.mp3")
artist7_album1_song7.track.attach(io: artist7_album1_song7_mp3, filename: '07 Shelter.mp3')
artist7_album1_song8 = Song.create(title: "Basic Space", length: 189, album_id: artist7_album1.id, explicit: false, album_order: 8)
artist7_album1_song8_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/The%20XX/xx/08%20Basic%20Space.mp3")
artist7_album1_song8.track.attach(io: artist7_album1_song8_mp3, filename: '08 Basic Space.mp3')
artist7_album1_song9 = Song.create(title: "Infinity", length: 314, album_id: artist7_album1.id, explicit: false, album_order: 9)
artist7_album1_song9_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/The%20XX/xx/09%20Infinity.mp3")
artist7_album1_song9.track.attach(io: artist7_album1_song9_mp3, filename: '09 Infinity.mp3')
artist7_album1_song10 = Song.create(title: "Night Time", length: 217, album_id: artist7_album1.id, explicit: false, album_order: 10)
artist7_album1_song10_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/The%20XX/xx/10%20Night%20Time.mp3")
artist7_album1_song10.track.attach(io: artist7_album1_song10_mp3, filename: '10 Night Time.mp3')
artist7_album1_song11 = Song.create(title: "Stars", length: 263, album_id: artist7_album1.id, explicit: false, album_order: 11)
artist7_album1_song11_mp3 = open("https://botify-dev.s3.us-east-2.amazonaws.com/ingest/The%20XX/xx/11%20Stars.mp3")
artist7_album1_song11.track.attach(io: artist7_album1_song11_mp3, filename: '11 Stars.mp3')


playlist1 = Playlist.create(title: "beep boop", owner_id: robot.id)
PlaylistSong.create(playlist_id: playlist1.id, song_id: artist1_album1_song1.id)
PlaylistSong.create(playlist_id: playlist1.id, song_id: artist6_album1_song2.id)
PlaylistSong.create(playlist_id: playlist1.id, song_id: artist7_album1_song1.id)
PlaylistSong.create(playlist_id: playlist1.id, song_id: artist7_album1_song9.id)
PlaylistSong.create(playlist_id: playlist1.id, song_id: artist3_album1_song5.id)

